spring.application.name=gestion-academica-api

# CONFIGURACION DE BD (variables de entorno)
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/gestionbd}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver

# CONFIGURACION JPA
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:none}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect